export enum PermissionStatus {
  CHEKING = "checking",
  GRANTED = "GRANTED",
  DENIED = "DENIED",
  BLOCKED = "BLOCKED",
  LIMITED = "LIMITED",
  UNAVAILABLE = "UNAVAILABLE",
  UNDETERMINED = "UNDETERMINED",
}
